name: Adding bin to artifacts

on:
    push:
        branches:
          - main 
    schedule:
        - cron: '0 0 1 */2 *'
    workflow_dispatch:

jobs:

    build:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout Code
            uses: actions/checkout@v3
          - name: Checkout
            uses: actions/checkout@v4
          - name: Install Rust nightly
            uses: dtolnay/rust-toolchain@master
            id: rust-toolchain
            with:
              toolchain: nightly

          - name: Build Release Binary
            run: cargo build --release

          - name: Upload Binary as Artifact
            uses: actions/upload-artifact@v3
            with:
              name: 42_connections
              path: target/release/ft_connections
    