name: Archiving Data for Minute

on:
  schedule:
    - cron: '*/11 * * * *' 
  workflow_dispatch:
    
jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Execute Binary
        run: ./ft_connections
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          SECRET_KEY_LOCATION: ${{ secrets.SECRET_KEY_LOCATION }}
          SECRET_ID_LOCATION: ${{ secrets.SECRET_ID_LOCATION }}
          SECRET_KEY_PROFIL: ${{ secrets.SECRET_KEY_PROFIL }}
          SECRET_ID_PROFIL: ${{ secrets.SECRET_ID_PROFIL }}
          RUST_LOG: info
